App\Entity\Product:
  properties:
    productAttribute:
      - Valid: ~
    title:
      - NotBlank: { message: 'valid.NotBlank'}
      - Type: string
      - Length:
          min: 4
          max: 255
    descr:
      - NotBlank: ~
      - Type: string
      - Length:
          min: 10
          max: 255
          minMessage: validators.NotBlank
    price:
      - NotBlank: ~
      - Type: integer
      - GreaterThan:
          value: 0
    amount:
      - NotBlank: ~
      - Type: integer
      - GreaterThan:
          value: 0
          message: validators.NotBlank
    user:
      - NotBlank: { groups: [create_product_console] }


App\Entity\ProductAttribute:
  properties:
    width:
      - Type: integer
      - GreaterThan:
          value: 0
    weight:
      - Type: integer
      - GreaterThan:
          value: 0
    length:
      - Type: integer
      - GreaterThan:
          value: 0
    height:
      - Type: integer
      - GreaterThan:
          value: 0

#App\Form\Object\ProductJson:
#  properties:
#    pathToJsonProduct:
#      - NotBlank: ~
#      - App\Validator\Constraints\IsEmailOrPhone: ~



App\Entity\Object\SearchProduct:
  properties:
    min_price:
#      - NotBlank: ~
#      - Type: integer
    max_price:
#      - NotBlank: ~
#      - Type: integer
    min_weight:
#      - NotBlank: ~
#      - Type: integer
    max_weight:
#      - NotBlank: ~
#      - Type: integer

App\Entity\Color:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
        fields: [color]
  properties:
    color:
      - NotBlank: ~